// change language of microseason labels - kanji default
var kanji = {
    "立春":["東風解凍", "黄鶯睍睆", "魚上氷"],
    "雨水":["土脉潤起", "霞始靆", "草木萌動"],
    "啓蟄":["蟄虫啓戸", "桃始笑", "菜虫化蝶"],
    "春分":["雀始巣", "櫻始開", "雷乃発声"],
    "清明":["玄鳥至", "鴻雁北", "虹始見"],
    "穀雨":["虹始見", "霜止出苗", "牡丹華"],
    "立夏":["蛙始鳴", "蚯蚓出", "竹笋生"],
    "小満":["蚕起食桑", "紅花栄", "麦秋至"],
    "芒種":["蟷螂生", "腐草為螢", "梅子黄"],
    "夏至":["乃東枯", "菖蒲華", "半夏生"],
    "小暑":["温風至", "蓮始開", "鷹乃学習"],
    "大暑":["桐始結花", "土潤溽暑", "大雨時行"],
    "立秋":["涼風至", "寒蝉鳴", "蒙霧升降"],
    "処暑":["綿柎開", "天地始粛", "禾乃登"],
    "白露":["草露白", "鶺鴒鳴", "玄鳥去"],
    "秋分":["雷乃収声", "蟄虫坏戸", "水始涸"],
    "寒露":["鴻雁来", "菊花開", "蟋蟀在戸"],
    "霜降":["霜始降", "霎時施", "楓蔦黄"], 
    "立冬":["山茶始開", "地始凍", "金盞香"],
    "小雪":["虹蔵不見", "朔風払葉", "橘始黄"],
    "大雪":["閉塞成冬", "熊蟄穴", "鱖魚群"],
    "冬至":["乃東生", "麋角解", "雪下出麦"],
    "小寒":["芹乃栄", "水泉動", "雉始雊"],
    "大寒":["款冬華", "水沢腹堅", "鶏始乳"]
}
var romaji = {
    "risshun":  ["harukaze kōri o toku", "kōō kenkan su", "uo kōri o izuru"],
    "usui":     ["tsuchi no shō uruoi okoru", "kasumi hajimete tanabiku", "sōmoku mebae izuru"],
    "keichitsu":["sugomori mushito o hiraku", "momo hajimete saku", "namushi chō to naru"],
    "shunbun":  ["suzume hajimete sukū", "sakura hajimete saku", "kaminari sunawachi koe o hassu"],
    "seimei":   ["tsubame kitaru", "kōgan kaeru", "niji hajimete arawaru"],
    "kokuu":    ["ashi hajimete shōzu", "shimo yamite nae izuru", "otan hana saku"],
    "rikka":    ["kawazu hajimete naku", "mimizu izuru", "takenoko shōzu"],
    "shōman":   ["kaiko okite kuwa o hamu", "benibana sakau", "mugi no toki itaru"],
    "bōshu":    ["kamakiri shōzu", "kusaretaru kusa hotaru to naru", "ume no mi kibamu"],
    "geshi":    ["natsukarekusa karuru", "ayame hana saku", "hange shōzu"],
    "shōsho":   ["atsukaze itaru", "hasu hajimete hiraku", "taka sunawachi waza o narau"],
    "taisho":   ["kiri hajimete hana o musubu", "tsuchi uruōte mushi atsushi", "taiu tokidoki furu"],
    "risshū":   ["suzukaze itaru", "higurashi naku", "fukaki kiri matō"],
    "shosho":   ["wata no hana shibe hiraku", "tenchi hajimete samushi", "kokumono sunawachi minoru"],
    "hakuro":   ["kusa no tsuyu shiroshi", "sekirei naku", "tsubame saru"],
    "shūbun":   ["kaminari sunawachi koe o osamu", "mushi kakurete to o fusagu", "mizu hajimete karuru"],
    "kanro":    ["kōgan kitaru", "kiku no hana hiraku", "kirigirisu to ni ari"],
    "sōkō":     ["shimo hajimete furu", "kosame tokidoki furu", "momiji tsuta kibamu"],
    "rittō":    ["tsubaki hajimete hiraku", "chi hajimete kōru", "kinsenka saku"],
    "shōsetsu": ["niji kakurete miezu", "kitakaze konoha o harau", "tachibana hajimete kibamu"],
    "taisetsu": ["sora samuku fuyu to naru", "kuma ana ni komoru", "sake no uo muragaru"],
    "tōji":     ["natsukarekusa shōzu", "sawashika no tsuno otsuru", "yuki watarite mugi nobiru"],
    "shōkan":   ["seri sunawachi sakau", "shimizu atataka o fukumu", "khimizu atataka o fukumu"],
    "daikan":   ["fuki no hana saku", "sawamizu kōri tsumeru", "niwatori hajimete toya ni tsuku"]
}
var english = {
    "beginning of spring":      ["east wind melts the ice", "bush warblers start singing in the mountains", "fish emerge from the ice"],
    "rainwater":                ["rain moistents the soil", "mist starts to linger", "grass sprouts, trees bud"],
    "insects awaken":           ["hibernating insects surface", "first peach blossoms", "caterpillars become butterflies"],
    "spring equinox":           ["sparrows start to nest", "first cherry blossoms", "distant thunder"],
    "pure and clear":           ["swallows return", "wild geese fly north", "first rainbows"],
    "grain rains":              ["first reeds sprout", "last frost, rice seedlings grow", "peonies bloom"],
    "beginning of summer":      ["frogs start singing", "worms surface", "bamboo shoots sprout"],
    "lesser ripening":          ["silkworms start feasting on mulberry leaves", "safflowers bloom", "wheat ripens and is harvested"],
    "grain beards and seeds":   ["praying mantises hatch", "rotten grass becomes fireflies", "plums turn yellow"],
    "summer solstice":          ["self-heal withers", "irises bloom", "crow-dipper sprouts"],
    "lesser heat":              ["warm winds blow", "first lotus blossoms", "hawks learn to fly"],
    "greater heat":             ["paulownia trees produce seeds", "earth is damp, air is humid", "great rains sometimes fall"],
    "beginning of autumn":      ["cool winds blow", "evening cicadas sing", "thick fog descends"],
    "manageable heat":          ["cotton flowers bloom", "heat starts to die down", "rice ripens"],
    "white dew":                ["dew glistens white on grass", "wagtails sing", "swallows leave"],
    "autumn equinox":           ["thunder ceases", "insects hole up underground", "farmers drain fields"],
    "cold dew":                 ["wild geese return", "chrysanthemums bloom", "crickets chirp around the door"],
    "frost falls":              ["first frost", "light rains sometimes fall", "maple leaves and ivy turn yellow"],
    "beginning of winter":      ["camellias bloom", "land starts to freeze", "daffodils bloom"],
    "lesser snow":              ["rainbows hide", "north wind blows the leaves from the trees", "tachibana citrus tree leaves start to turn yellow"],
    "greater snow":             ["cold sets in, winter begins", "beats start hibernating in their dens", "salmon gather and swim upstream"],
    "winter solstice":          ["self-heal sprouts", "deer shed antlers", "wheat sprouts under snow"],
    "lesser cold":              ["parsley flourishes", "springs thaw", "pheasants start to call"],
    "greater cold":             ["butterburs bud", "ice thickens on streams", "hens start laying eggs"]
}